### ISSUE TITLE
Error while login on android emulator

### ISSUE THREAD

**Issue by ernado-x** [DOIS/ecampus-client-android#14]
01-22 03:25:17.792     911-1121/ua.kpi.campus E/error﹕ org.json.JSONException: Index 0 out of range [0..0)
01-22 03:25:17.792     911-1121/ua.kpi.campus W/System.err﹕ org.json.JSONException: Index 0 out of range [0..0)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at org.json.JSONArray.get(JSONArray.java:282)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at org.json.JSONArray.getJSONObject(JSONArray.java:510)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at ua.kpi.campus.api.GetCurrentUser.doInBackground(GetCurrentUser.java:58)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at ua.kpi.campus.api.GetCurrentUser.doInBackground(GetCurrentUser.java:35)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-22 03:25:17.812     911-1121/ua.kpi.campus W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
01-22 03:25:17.822     911-1121/ua.kpi.campus D/SyncSchedule﹕ Trying to get items
01-22 03:25:17.982     911-1121/ua.kpi.campus D/SyncSchedule﹕ Reading lines...
01-22 03:25:17.982     911-1121/ua.kpi.campus W/System.err﹕ org.json.JSONException: Value {"message":"Lessons not found","timeStamp":1421915117,"statusCode":404} of type org.json.JSONObject cannot be converted to JSONArray
01-22 03:25:17.992     911-1121/ua.kpi.campus W/System.err﹕ at org.json.JSON.typeMismatch(JSON.java:111)
01-22 03:25:17.992     911-1121/ua.kpi.campus W/System.err﹕ at org.json.JSONArray.<init>(JSONArray.java:96)
01-22 03:25:17.992     911-1121/ua.kpi.campus W/System.err﹕ at org.json.JSONArray.<init>(JSONArray.java:108)
01-22 03:25:17.992     911-1121/ua.kpi.campus W/System.err﹕ at ua.kpi.campus.api.SyncSchedule.getSchedule(SyncSchedule.java:96)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at ua.kpi.campus.api.SyncSchedule$Connect.doInBackground(SyncSchedule.java:203)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at ua.kpi.campus.api.SyncSchedule$Connect.doInBackground(SyncSchedule.java:183)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:288)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
01-22 03:25:18.002     911-1121/ua.kpi.campus W/System.err﹕ at java.lang.Thread.run(Thread.java:841)

**Comment by Deepnekroz** [comment]
Will be fixed soon. Error happens when trying to get Student-type schedule for Teacher account.
