### ISSUE TITLE
Not building in Intellij IDEA 14

### ISSUE THREAD

**Issue by doroshartyom** [DOIS/ecampus-client-android#5]
Can't build app in Intellij IDEA 14. Add build instructions to README.md or Wiki

**Comment by infm** [comment]
@doroshartyom seems like it's a [problem](http://stackoverflow.com/questions/27766025/android-studio-1-0-2-new-project-cannot-resolve-symbol-actionbaractivity) with AS 1.0.2 (I've encountered exactly the same problem when tried to import)

**Comment by infm** [comment]
Well, I've finally figured it out.
#### To import that project into IDE older than the latest AS:
1. Change `classpath 'com.android.tools.build:gradle:1.0.0'` version to `0.14.2` or older in top level `build.gradle` file.
2. Set the language level 8 for the entire project (e.g. to support implicit type parameters).

**Comment by doroshartyom** [comment]
Closed in last pull request
