### ISSUE TITLE
Login w/o account wrong behavior

### ISSUE THREAD

**Issue by OlexandrKovalchuk** [DOIS/ecampus-client-android#9]
How to reproduce:
Accept license agrement -> proceed to LoginActivity -> Click "Have no account?" -> When app asks to enter group, click "Close". Then restart application and discover, that login (in guest mode) was successful, and some group's schedule is displayed

Which behavior expected:
Instead of seeing unknown group's schedule, user wants to see either login view (login & pwd) or group selection view (group name)

Reason:
LoginActivity.java line 42: `PrefUtils.markAuthPassed(getApplicationContext());` Application marks auth as passed even if user has not finished it (has not selected his group)
BaseActivity.java line 442: `SyncSchedule sync = SyncSchedule.getSyncSchedule("ФБ-41", getApplicationContext());` Hardcoded default group name

**Comment by doroshartyom** [comment]
This wasn't implemented. Will be implemented today.

**Comment by Deepnekroz** [comment]
Fixed

**Comment by ernado-x** [comment]
@Deepnekroz , you can link commit to Issue by use commit message "Close #9"
